name: Build and Test on PR

on:
  pull_request:
    branches: 
      - master
      - integration/*
      
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli
      
      - name: Install Dependencies
        run: npm ci

      - name: Test App
        run: npm run test

      - name: Build App
        run: npm run build -- --prod --outputPath dist
