name: Dev Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm ci

      - name: Build App
        run: npm run build -- --prod --outputPath dist

      - name: Authenticate with Google Cloud
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > key.json

      - name: Deploy to GCS 
        run: |
          gcloud auth activate-service-account --key-file=key.json
          gsutil -m cp -r dist/* gs://${{ vars.BUCKET_NAME }}
