name: TESTING

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch (optional, defaults to main)'
        required: false
        default: 'main'
      environment:
        type: environment
        options:
          - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Print message using echo
        run: echo "${{ vars.NAME }}"
