name: Build and Deploy Angular App to GCS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Target branch (optional, defaults to main)'
        required: false
        default: 'main'
      environment:
        type: environment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print message using echo
        run: echo "${ vars.NAME }"
